config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users
  root 'articles#index'
  resources :users, only: [:edit, :update]
  resources :artists, only: [:index, :new, :show,]
  resources :videos, only: [:index, :show]
  resources :articles, only: [:index, :show]

  get '/users/:id' => 'users#index', as: 'users'

  post '/follow_users/:artist_id' => 'follow_users#create', as: 'follow'
  delete '/follow_users/:artist_id' => 'follow_users#destroy', as: 'unfollow'

  post '/favorite_videos/:video_id' => 'favorite_videos#create', as: 'add_favorite_video'
  delete '/favorite_videos/:video_id' => 'favorite_videos#destroy', as: 'remove_favorite_video'

  post '/favorite_articles/:article_id' => 'favorite_articles#create', as: 'add_favorite_article'
  delete '/favorite_artcles/:article_id' => 'favorite_articles#destroy', as: 'remove_favorite_article'

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin_flg?
      can :access, :rails_admin
      can :manage, :all
    end
  end
end

app/models/apple_music.rb
class AppleMusic < ApplicationRecord
  belongs_to :artist
  belongs_to :article
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :artist
  has_many :favorite_articles, dependent: :destroy
  has_many :users, through: :favorite_articles
  has_many :apple_musics, dependent: :destroy
  has_many :soundclouds, dependent: :destroy
  has_many :videos, dependent: :destroy
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :follow_users, dependent: :destroy
  has_many :users, through: :follow_users
  has_many :videos, dependent: :destroy
  has_many :articles, dependent: :destroy
  has_many :apple_musics, dependent: :destroy
  has_many :soundclouds, dependent: :destroy
end

app/models/favorite_article.rb
class FavoriteArticle < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/favorite_video.rb
class FavoriteVideo < ApplicationRecord
  belongs_to :user
  belongs_to :video
end

app/models/follow_user.rb
class FollowUser < ApplicationRecord
  belongs_to :user
  belongs_to :artist
end

app/models/soundcloud.rb
class Soundcloud < ApplicationRecord
  belongs_to :artist
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :follow_users, dependent: :destroy
  has_many :artists, through: :follow_users
  has_many :favorite_videos, dependent: :destroy
  has_many :videos, through: :favorite_videos
  has_many :favorite_articles, dependent: :destroy
  has_many :articles, through: :favorite_articles
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :artist
  belongs_to :article
  has_many :favorite_videos, dependent: :destroy
  has_many :users, through: :favorite_videos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_parmitted_parameters, if: :devise_controller?

  def configure_parmitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController 
  before_action :set_article, only: [:show]
  before_action :set_artist, only: [:show]

  def index
    @articles = Article.order("id DESC").limit(8)
    last_article_id = params[:id]
    @next = Article.where("id < #{last_article_id}", params[:id])
    respond_to do |format|
      format.html
      format.json 
    end
  end

  def show
    @articles = @artist.articles.where.not(id: @article.id)
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def set_artist
    @artist = Article.find(params[:id]).artist
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: :show

  def index
    @artists = Artist.order(:name)
  end

  def new
    @artist = Artist.new
  end

  def show
  end

  private

  def set_artist
    @artist = Artist.find(params[:id])
  end

end

app/controllers/favorite_articles_controller.rb
class FavoriteArticlesController < ApplicationController
  before_action :set_article

  def create
    favorite = current_user.favorite_articles.new(article_id: @article.id)
    favorite.save
  end

  def destroy
    favorite = current_user.favorite_articles.find_by(article_id: @article.id)
    favorite.destroy
  end

  private

  def set_article
    @article = Article.find(params[:article_id])
  end
  
end

app/controllers/favorite_videos_controller.rb
class FavoriteVideosController < ApplicationController
  before_action :set_video

  def create
    favorite = current_user.favorite_videos.new(video_id: @video.id)
    favorite.save
  end

  def destroy
    favorite = current_user.favorite_videos.find_by(video_id: @video.id)
    favorite.destroy
  end

  private

  def set_video
    @video = Video.find(params[:video_id])
  end

end

app/controllers/follow_users_controller.rb
class FollowUsersController < ApplicationController
  before_action :set_artist

  def create
    follow = current_user.follow_users.new(artist_id: @artist.id)
    follow.save
  end

  def destroy
    follow = current_user.follow_users.find_by(artist_id: @artist.id)
    follow.destroy
  end

  private

  def set_artist
    @artist = Artist.find(params[:artist_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @artists = current_user.artists
    @videos = current_user.videos
    @articles = current_user.articles
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else 
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_artist, only: [:show]

  def index
    @videos = Video.order("id DESC").limit(8)
    last_video_id = params[:id]
    @next = Video.where("id < #{last_video_id}", params[:id])
    respond_to do |format|
      format.html
      format.json 
    end
  end

  def show
    @video = Video.find(params[:id])
    @videos = @artist.videos.where.not(id: @video.id)
  end


  private

  def set_artist
    @artist = Video.find(params[:id]).artist
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.haml
.main
  .articles
    .articles__title-box
      %h1.articles__title-box__title LATEST ARTICLES
      %span.articles__title-box__double-line
    .articles__articles-box
      .articles__articles-box__wrapper
        - @articles.each do |article|
          = link_to article_path(article), class: "article",data: {id: article.id} do
            = render "shared/articles-list", article: article
    .articles__button-box
      .articles__button-box__back-btn MORE ARTICLES

app/views/articles/show.html.haml
.main
  .article-show
    .article-show__head-box
      %h1.article-show__head-box__title
        = @article.title
      %span.article-show__head-box__double-line
    .article-show__image-box
      = image_tag @article.image, class: "article-show__image-box__image"
    .article-show__text-box
      %span.article-show__text-box__single-line
      %p.article-show__text-box__text
        = safe_join(@article.text.split("\n"), tag(:br))
      - if !@article.videos.empty?
        - @article.videos.each do |video|
          .article-show__text-box__video
            %iframe(src="https://www.youtube.com/embed/#{video.videoID}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen)
      - if !@article.apple_musics.empty?
        - @article.apple_musics.each do |apple_music|
          .article-show__text-box__apple-music
            %iframe(src="#{apple_music.link}" allow="autoplay *; encrypted-media *;" frameborder="0" height="300" style="width:100%;max-width:900px;overflow:hidden;background:transparent;" sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-storage-access-by-user-activation allow-top-navigation-by-user-activation")
      - if !@article.soundclouds.empty?
        - @article.soundclouds.each do |soundcloud|
          .article-show__text-box__soundcloud
            %iframe(width="100%" height="#{soundcloud.player_height}" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=#{soundcloud.link}&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true")
      %span.article-show__text-box__single-line
    - if user_signed_in?
      .article-show__button-box{id: "favorite-article-btn-#{@article.id}"}
        = render "shared/favorite-article-button", article: @article
    .article-show__related-artist-box
      %h2.article-show__related-artist-box__title Related Artist
      %span.article-show__related-artist-box__single-line
      = image_tag @article.artist.image, class: "article-show__related-artist-box__image"
      .article-show__related-artist-box__name-box
        %span.article-show__related-artist-box__name-box__single-line
        = link_to "#{@article.artist.name}", artist_path(@article.artist), class: "article-show__related-artist-box__name-box__name"
        %span.article-show__related-artist-box__name-box__single-line
    - if !@articles.empty?
      .article-show__related-articles-box
        %h2.article-show__related-articles-box__title
          = "Related articles"
        %span.article-show__related-articles-box__single-line
        .article-show__related-articles-box__wrapper
          - @articles.each do |article|
            = link_to article_path(article), class: "article-show__related-articles-box__wrapper__article" do
              = render "shared/articles-list", article: article
        %span.article-show__related-articles-box__single-line
    .article-show__button-box
      = link_to "BACK", articles_path, class: "article-show__button-box__back-btn"

app/views/artists/index.html.haml
.main
  .artists
    .artists__title-box
      %h1.artists__title-box__title ARTISTS
      %span.artists__title-box__double-line
    .artists__artists-box
      .artists__artists-box__wrapper
        - @artists.each do |artist|
          = link_to artist_path(artist), class: "artist" do
            = render "shared/artists-list", artist: artist

app/views/artists/new.html.haml
= form_for(@artist, method: :POST) do |f|
  .form-box-update
    .artist-form
      .artist-form__header
        %h2 REGISTER NEW ARTIST
        %span.double-line--black
      .artist-form__box
        .artist-form__box__name
          = f.label :name
          = f.text_field :name, autofocus: true
        .artist-form__box__image
          = f.label :image
          = f.text_field :image
        .artist-form__box__text
          = f.label :text
          = f.text_area :text
      .artist-form__submit
        = f.submit "REGISTER"

app/views/artists/show.html.haml
.main
  .artist-data
    .artist-data__title-box 
      %h1.artist-data__title-box__name
        = @artist.name
      %span.artist-data__title-box__double-line
    .artist-data__image-box
      = image_tag @artist.image, class: "artist-data__image-box__image"
    - if user_signed_in?
      .artist-data__button-box{id: "follow-id-#{@artist.id}"}
        = render "shared/follow-button", artist: @artist
    .artist-data__text-box
      %span.artist-data__text-box__single-line
      %p.artist-data__text-box__text
        = safe_join(@artist.text.split("\n"), tag(:br))
      %span.artist-data__text-box__single-line
    .artist-data__articles-box
      %h2.artist-data__articles-box__title ARTICLES
      %span.artist-data__articles-box__single-line
      - if @artist.articles.empty?
        %p.artist-data__articles-box__message
          = "No articles"
      - else
        .artist-data__articles-box__wrapper
          - @artist.articles.each do |article|
            = link_to article_path(article), class: "article" do
              = render "shared/articles-list", article: article
      %span.artist-data__articles-box__single-line
    .artist-data__videos-box
      %h2.artist-data__videos-box__title VIDEOS
      %span.artist-data__videos-box__single-line
      - if @artist.videos.empty?
        %p.artist-data__videos-box__message
          = "No videos"
      - else
        .artist-data__videos-box__wrapper
          - @artist.videos.each do |video|
            = link_to video_path(video), class: "video" do
              = render "shared/videos-list", video: video
      %span.artist-data__videos-box__single-line
    .artist-data__button-box
      = link_to "BACK", artists_path, class: "artist-data__button-box__back-btn"
    

app/views/favorite_articles/create.js.erb
$("#favorite-article-btn-<%= @article.id %>").html("<%= j(render "shared/favorite-article-button", article: @article ) %>")

app/views/favorite_articles/destroy.js.erb
$("#favorite-article-btn-<%= @article.id %>").html("<%= j(render "shared/favorite-article-button", article: @article ) %>")

app/views/favorite_videos/create.js.erb
$("#favorite-video-btn-<%= @video.id %>").html("<%= j(render "shared/favorite-video-button", video: @video) %>")

app/views/favorite_videos/destroy.js.erb
$("#favorite-video-btn-<%= @video.id %>").html("<%= j(render "shared/favorite-video-button", video: @video) %>")

app/views/follow_users/create.js.erb
$("#follow-id-<%= @artist.id %>").html("<%= j(render "shared/follow-button", artist: @artist) %>")

app/views/follow_users/destroy.js.erb
$("#follow-id-<%= @artist.id %>").html("<%= j(render "shared/follow-button", artist: @artist) %>")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MyApp
    = csrf_meta_tags
    %link{:href => "https://use.fontawesome.com/releases/v5.6.3/css/all.css", :rel => "stylesheet"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render "shared/header"
    = yield

app/views/shared/_articles-list.html.haml
.article__inner
  .article__inner__image
    = image_tag article.image
  .article__inner__text-box
    %h2.article__inner__text-box__title
      = article.title
    %p.article__inner__text-box__date
      = article.created_at.strftime("%Y/%m/%d")

app/views/shared/_artists-list.html.haml
.artist__inner
  .artist__inner__thumnail
    = image_tag artist.image
  .artist__inner__details
    %p.artist__inner__details__artist-name
      = artist.name
    

app/views/shared/_favorite-article-button.html.haml
- if current_user.favorite_articles.find_by(article_id: article.id)
  = link_to "YOUR FAVORITE", remove_favorite_article_path(article.id), method: :delete, class: "article-show__button-box__remove-favorite-btn", remote: true
- else
  = link_to "ADD FAVORITE", add_favorite_article_path(article.id), method: :post, class: "article-show__button-box__add-favorite-btn", remote: true

app/views/shared/_favorite-video-button.html.haml
- if current_user.favorite_videos.find_by(video_id: video.id)
  = link_to "YOUR FAVORITE", remove_favorite_video_path(video.id), method: :delete, class: "video-show__button-box__remove-favorite-btn", remote: true
- else
  = link_to "ADD FAVORITE", add_favorite_video_path(video.id), method: :post, class: "video-show__button-box__add-favorite-btn", remote: true

app/views/shared/_follow-button.html.haml
- if current_user.follow_users.find_by(artist_id: artist.id)
  = link_to "FOLLOWING", follow_path(artist.id), method: :delete, class: "artist-data__button-box__following-btn", remote: true
- else
  = link_to "FOLLOW", follow_path(artist.id), method: :post, class: "artist-data__button-box__follow-btn", remote: true

app/views/shared/_header.html.haml
%header.header
  .header__wrapper
    = link_to "", root_path, class: "header__wrapper__logo"
    .menu
      #default-menu
        %ul.menu__list
          %li.menu__list__link
            = link_to "ARTICLES", articles_path
          %li.menu__list__link
            = link_to "ARTISTS", artists_path
          %li.menu__list__link
            = link_to "VIDEOS", videos_path
          - if user_signed_in?
            %li.menu__list__link
              = link_to "MY PAGE", users_path(current_user)
          %li.menu__list__btn
            = fa_icon "user"
      #user-menu
        %ul.menu__list
          - if user_signed_in?
            %li.menu__list__link
              %p.menu__list__link--user-name
                = "Welcome, #{current_user.name}!"
            - if current_user != nil && current_user.admin_flg?
              %li.menu__list__link
                = link_to "ADMIN", "/admin", target: :_blank
            %li.menu__list__link
              = link_to "EDIT ACCOUNT", edit_user_path(current_user)
            %li.menu__list__link
              = link_to "LOG OUT", destroy_user_session_path, method: :delete
          - else 
            %li.menu__list__link
              = link_to "SIGN UP", new_user_registration_path
            %li.menu__list__link
              = link_to "LOG IN", new_user_session_path
          %li.menu__list__btn
            = fa_icon "times"

app/views/shared/_videos-list.html.haml
.video__inner
  .video__inner__thumnail
    = image_tag "http://img.youtube.com/vi/#{video.videoID}/mqdefault.jpg"
  .video__inner__details
    %p.video__inner__details__song-title
      = video.title
    %p.video__inner__details__artist-name
      = video.artist.name
    %p.video__inner__details__date
      = video.created_at.strftime("%Y/%m/%d")

app/views/users/edit.html.haml
.account-page
  .account-page__inner
    .account-page__header 
      %h2 EDIT ACCOUNT
    %span.double-line--white
    = form_for(current_user) do |f|
      .user-form
        .field-label
          = f.label :name
        .field-input
          = f.text_field :name, autofocus: true
        .field-label
          = f.label :email
        .field-input
          = f.email_field :email
      .field-update
        = f.submit "Update", class: 'field-update__btn'

app/views/users/index.html.haml
.main
  .mypage
    .mypage__title-box
      %h1.mypage__title-box__title
        = current_user.name
      %span.mypage__title-box__double-line
    .mypage__favorite-artists-box
      %h2.mypage__favorite-artists-box__title FAVORITE ARTISTS
      %span.mypage__favorite-artists-box__single-line
      .mypage__favorite-artists-box__artists
        - if @artists.empty?
          %p.mypage__favorite-artists-box__artists__message
            = "NO FOLLOWING ARTISTS"
        - else
          .mypage__favorite-artists-box__artists__wrapper
            - @artists.each do |artist|
              = link_to artist_path(artist), class: "favorite-artist" do
                = render "shared/artists-list", artist: artist
      %span.mypage__favorite-artists-box__single-line
    .mypage__favorite-articles-box
      %h2.mypage__favorite-articles-box__title FAVORITE ARTICLES
      %span.mypage__favorite-articles-box__single-line
      .mypage__favorite-articles-box__articles
        - if @articles.empty?
          %p.mypage__favorite-articles-box__articles__message
            = "NO FAVORITE ARTICLES"
        - else
          .mypage__favorite-articles-box__articles__wrapper
            - @articles.each do |article|
              = link_to article_path(article), class: "article" do
                = render "shared/articles-list", article: article
      %span.mypage__favorite-articles-box__single-line
    .mypage__favorite-videos-box
      %h2.mypage__favorite-videos-box__title FAVORITE VIDEOS
      %span.mypage__favorite-videos-box__single-line
      .mypage__favorite-videos-box__videos
        - if @videos.empty?
          %p.mypage__favorite-videos-box__videos__message
            = "NO FAVORITE VIDEOS"
        - else
          .mypage__favorite-videos-box__videos__wrapper
            - @videos.each do |video|
              = link_to video_path(video), class: "video" do
                = render "shared/videos-list", video: video
      %span.mypage__favorite-videos-box__single-line

app/views/videos/index.html.haml
.main
  .main__black-box
    .videos
      .videos__title-box
        %h1.videos__title-box__title LATEST VIDEOS
        %span.videos__title-box__double-line
      .videos__videos-box
        .videos__videos-box__wrapper
          - @videos.each do |video|
            = link_to video_path(video), class: "video", data: {id: video.id} do
              = render "shared/videos-list", video: video
      .videos__button-box
        .videos__button-box__more-btn MORE VIDEOS

app/views/videos/show.html.haml
.main
  .main__black-box
    .video-show
      .video-show__title-box
        %h1.video-show__title-box__title
          = "#{@video.artist.name} - #{@video.title}"
        %span.video-show__title-box__double-line
      .video-show__player-box
        .video-show__player-box__iframe
          %iframe(src="https://www.youtube.com/embed/#{@video.videoID}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen)
      - if user_signed_in?
        .video-show__button-box{id: "favorite-video-btn-#{@video.id}"}
          = render "shared/favorite-video-button", video: @video
      .video-show__artist-box
        %h2.video-show__artist-box__title Starring Artist
        %span.video-show__artist-box__single-line
        = image_tag @video.artist.image, class: "video-show__artist-box__image"
        .video-show__artist-box__name-box
          %span.video-show__artist-box__name-box__single-line
          = link_to "#{@video.artist.name}", artist_path(@video.artist), class: "video-show__artist-box__name-box__name"
          %span.video-show__artist-box__name-box__single-line
      - if !@videos.empty?
        .video-show__other-videos-box
          %h2.video-show__other-videos-box__message
            = "Other videos of #{@video.artist.name}"
          %span.video-show__other-videos-box__single-line
          .video-show__other-videos-box__wrapper
            - @videos.each do |video|
              = link_to video_path(video), class: "other-video" do
                = render "shared/videos-list", video: video
          %span.video-show__other-videos-box__single-line
      .video-show__button-box
        = link_to "BACK", videos_path, class: "video-show__button-box__back-btn"